# Generated by Django 5.1.2 on 2024-11-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_number', models.PositiveSmallIntegerField()),
                ('region_name', models.CharField(max_length=200)),
                ('population_size', models.PositiveBigIntegerField()),
                ('area', models.FloatField()),
                ('capital_city', models.CharField(max_length=200)),
                ('flag', models.ImageField(upload_to='flag')),
                ('email', models.EmailField(max_length=254)),
                ('map', models.ImageField(upload_to='map')),
                ('website', models.URLField()),
            ],
        ),
    ]
